import React, { useState, useEffect } from 'react';
import { useAuth } from '../context/AuthContext';
import { useApp } from '../context/AppContext';
import { api } from '../services/api';
import { Mascot } from '../components/Mascot';
import { ReminderSystem } from '../components/ReminderSystem';
import { Flame, Trophy, Award, Sparkles, BookOpen, CheckCircle, Clock, Plus, Trash, Calendar, AlertTriangle, Lightbulb } from 'lucide-react';

export const StudentDashboard = () => {
  const { user, refreshUser } = useAuth();
  const { navigate, triggerNotification, t } = useApp();

  const [profile, setProfile] = useState(null);
  const [activePlan, setActivePlan] = useState(null);
  const [exams, setExams] = useState([]);
  const [homework, setHomework] = useState([]);
  const [loadingPlan, setLoadingPlan] = useState(false);

  // Form states
  const [showAddHw, setShowAddHw] = useState(false);
  const [newHwTitle, setNewHwTitle] = useState('');
  const [newHwSubject, setNewHwSubject] = useState('Mathematics');
  const [newHwDueDate, setNewHwDueDate] = useState('');

  const [showAddExam, setShowAddExam] = useState(false);
  const [newExamTitle, setNewExamTitle] = useState('');
  const [newExamSubject, setNewExamSubject] = useState('Mathematics');
  const [newExamDate, setNewExamDate] = useState('');

  const loadDashboardData = async () => {
    try {
      // 1. Get Student Profile from MongoDB
      const profileData = await api.getStudentProfile();
      setProfile(profileData);

      // 2. Get Active Daily Plan
      const plan = await api.getActiveStudyPlan('daily');
      setActivePlan(plan);

      // 3. Get Exams
      const examData = await api.getExams();
      setExams(examData || []);

      // 4. Get Homeworks
      const homeworkData = await api.getHomework();
      setHomework(homeworkData || []);
    } catch (err) {
      console.error("Error loading dashboard data:", err);
    }
  };

  useEffect(() => {
    loadDashboardData();
  }, []);

  const handleGeneratePlan = async () => {
    setLoadingPlan(true);
    try {
      const res = await api.generateStudyPlan();
      triggerNotification('✨ Study plan successfully generated by Study Planner Agent!', 'purple');
      // Reload active plan
      const plan = await api.getActiveStudyPlan('daily');
      setActivePlan(plan);
      loadDashboardData();
    } catch (err) {
      triggerNotification('❌ Failed to generate plan: ' + err.message, 'red');
    } finally {
      setLoadingPlan(false);
    }
  };

  const handleCompleteTask = async (taskIndex) => {
    if (!activePlan) return;
    try {
      const updatedTasks = [...activePlan.planData.tasks];
      const task = updatedTasks[taskIndex];
      if (task.completed) return; // already done

      task.completed = true;
      
      // Award 20 XP for plan task completion
      await api.awardXp(20, `Completed task: ${task.topic}`);
      triggerNotification(`🌟 Plan task completed! +20 XP!`, 'green');
      
      // Update plan in DB or mock list
      // For simulation/mock mode we update state, the backend has saved the state change in progress logging
      setActivePlan({
        ...activePlan,
        planData: {
          ...activePlan.planData,
          tasks: updatedTasks
        }
      });
      loadDashboardData();
      refreshUser();
    } catch (err) {
      console.error("Error completing plan task:", err);
    }
  };

  const handleAddHomework = async (e) => {
    e.preventDefault();
    if (!newHwTitle.trim() || !newHwDueDate) {
      triggerNotification("Please fill in homework details.", "red");
      return;
    }
    try {
      const item = await api.createHomework(newHwTitle, newHwSubject, newHwDueDate);
      setHomework(prev => [item, ...prev]);
      setNewHwTitle('');
      setNewHwDueDate('');
      setShowAddHw(false);
      triggerNotification('✏️ Homework tracked successfully!', 'green');
    } catch (err) {
      console.error(err);
    }
  };

  const handleToggleHomework = async (hwId, currentStatus) => {
    try {
      await api.updateHomework(hwId, !currentStatus);
      setHomework(prev => prev.map(h => h._id === hwId ? { ...h, completed: !currentStatus } : h));
      triggerNotification(!currentStatus ? '✅ Homework completed! +10 Coins!' : '✏️ Homework set back to active.');
      if (!currentStatus) {
        // Award XP and coins
        await api.awardXp(10, `Homework Complete`);
      }
      loadDashboardData();
      refreshUser();
    } catch (err) {
      console.error(err);
    }
  };

  const handleDeleteHomework = async (hwId) => {
    try {
      await api.deleteHomework(hwId);
      setHomework(prev => prev.filter(h => h._id !== hwId));
      triggerNotification('🗑️ Homework deleted.');
    } catch (err) {
      console.error(err);
    }
  };

  const handleAddExam = async (e) => {
    e.preventDefault();
    if (!newExamTitle.trim() || !newExamDate) {
      triggerNotification("Please fill in exam details.", "red");
      return;
    }
    try {
      const item = await api.createExam({
        subject: newExamSubject,
        title: newExamTitle,
        date: newExamDate
      });
      setExams(prev => [...prev, item]);
      setNewExamTitle('');
      setNewExamDate('');
      setShowAddExam(false);
      triggerNotification('📅 Exam scheduled successfully!', 'purple');
    } catch (err) {
      console.error(err);
    }
  };

  const handleDeleteExam = async (examId) => {
    try {
      await api.deleteExam(examId);
      setExams(prev => prev.filter(e => e._id !== examId));
      triggerNotification('🗑️ Exam schedule removed.');
    } catch (err) {
      console.error(err);
    }
  };

  // Safe fallback profile values
  const studentProfile = profile || {
    name: user?.name || 'Student',
    classNum: 5,
    xp: 0,
    coins: 0,
    streak: 0,
    schoolName: '',
    schoolType: 'Public',
    board: 'SSC',
    weakSubjects: ['Mathematics'],
    strongSubjects: ['Science'],
    learningGoals: []
  };

  const calculatedLevel = Math.floor((studentProfile.xp || 0) / 100) + 1;
  const xpInCurrentLevel = (studentProfile.xp || 0) % 100;

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '30px' }}>
      
      {/* Top Profile Stats Bar */}
      <section style={{
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
        gap: '20px'
      }}>
        {/* Streak card */}
        <div className="card-buddy" style={{
          display: 'flex', alignItems: 'center', gap: '16px',
          background: 'linear-gradient(135deg, #fff3e0 0%, #ffe0b2 100%)',
          borderColor: '#ffe0b2'
        }}>
          <div className="animate-flame" style={{ color: '#ff6d00' }}>
            <Flame size={40} fill="currentColor" />
          </div>
          <div>
            <h4 style={{ fontSize: '1.3rem', color: '#e65100' }}>
              {studentProfile.streak} {t('streak')}
            </h4>
            <p style={{ color: '#ff6d00', fontSize: '0.8rem', fontWeight: 'bold' }}>
              {studentProfile.streak > 0 ? "You're on fire! 🔥 Keep it up!" : "Start a streak today! 🚀"}
            </p>
          </div>
        </div>

        {/* XP / Level card */}
        <div className="card-buddy" style={{
          display: 'flex', flexDirection: 'column', gap: '10px',
          background: 'linear-gradient(135deg, #e8f5e9 0%, #c8e6c9 100%)',
          borderColor: '#c8e6c9'
        }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <h4 style={{ fontSize: '1.15rem', color: '#1b5e20', display: 'flex', alignItems: 'center', gap: '6px' }}>
              <Trophy size={18} fill="currentColor" /> {studentProfile.xp} {t('xp')}
            </h4>
            <span style={{ fontSize: '0.8rem', fontWeight: 'bold', color: '#2e7d32', backgroundColor: '#a5d6a7', padding: '2px 8px', borderRadius: '12px' }}>
              {t('level')} {calculatedLevel}
            </span>
          </div>
          <div>
            <div className="progress-bar-container" style={{ backgroundColor: '#ffffff', height: '10px' }}>
              <div className="progress-bar-fill" style={{ width: `${xpInCurrentLevel}%`, backgroundColor: 'var(--color-green)' }} />
            </div>
            <p style={{ fontSize: '0.75rem', color: '#2e7d32', marginTop: '4px', textAlign: 'right', fontWeight: 'bold' }}>
              {100 - xpInCurrentLevel} XP to Level {calculatedLevel + 1}
            </p>
          </div>
        </div>

        {/* Coins Wallet card */}
        <div className="card-buddy" style={{
          display: 'flex', alignItems: 'center', gap: '14px',
          background: 'linear-gradient(135deg, #fffde7 0%, #fff9c4 100%)',
          borderColor: '#fff9c4'
        }}>
          <div style={{ fontSize: '2rem' }}>🪙</div>
          <div>
            <h4 style={{ fontSize: '1.3rem', color: '#f57f17' }}>
              {studentProfile.coins || 0} {t('coins')}
            </h4>
            <p style={{ color: '#e65100', fontSize: '0.8rem', fontWeight: 'bold' }}>
              Earned from study achievements!
            </p>
          </div>
        </div>

        {/* Dashboard Badge Cabinet Link */}
        <div className="card-buddy" style={{
          display: 'flex', alignItems: 'center', gap: '14px',
          background: 'linear-gradient(135deg, #f3e5f5 0%, #e1bee7 100%)',
          borderColor: '#e1bee7'
        }}>
          <div style={{ color: 'var(--color-purple)' }}>
            <Award size={40} fill="currentColor" />
          </div>
          <div>
            <h4 style={{ fontSize: '1.1rem', color: '#4a148c' }}>
              Badges Shelf
            </h4>
            <button 
              onClick={() => navigate('progress')} 
              style={{ background: 'none', border: 'none', color: 'var(--color-purple)', fontSize: '0.8rem', fontWeight: 'bold', cursor: 'pointer', textDecoration: 'underline', padding: 0 }}
            >
              Check Cabinet →
            </button>
          </div>
        </div>
      </section>

      {/* Main Layout Grid */}
      <div className="dashboard-grid">
        
        {/* Left Column: Today's Study Plan & Upcoming Exams */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '30px' }}>
          
          {/* Today's Study Plan (AI Powered) */}
          <section className="card-buddy">
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '1.5px solid var(--border-light)', paddingBottom: '10px', marginBottom: '15px' }}>
              <h3 style={{ fontSize: '1.35rem', display: 'flex', alignItems: 'center', gap: '8px', color: 'var(--text-main)' }}>
                <Sparkles size={20} fill="var(--color-yellow)" color="var(--color-yellow)" /> Today's AI Study Plan
              </h3>
              
              <button 
                onClick={handleGeneratePlan}
                disabled={loadingPlan}
                className="btn-3d btn-3d-purple"
                style={{ padding: '6px 14px', fontSize: '0.8rem' }}
              >
                {loadingPlan ? 'Planning...' : '✨ Generate Plan'}
              </button>
            </div>

            {activePlan && activePlan.planData && activePlan.planData.tasks && activePlan.planData.tasks.length > 0 ? (
              <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
                <p style={{ color: 'var(--text-muted)', fontSize: '0.82rem', marginBottom: '8px' }}>
                  Complete your tasks to earn **+20 XP** per topic!
                </p>
                {activePlan.planData.tasks.map((task, idx) => (
                  <div
                    key={idx}
                    onClick={() => handleCompleteTask(idx)}
                    style={{
                      display: 'flex', alignItems: 'center', gap: '12px',
                      padding: '14px', borderRadius: 'var(--radius-sm)',
                      backgroundColor: task.completed ? 'var(--color-green-light)' : 'var(--bg-app)',
                      border: `2.5px solid ${task.completed ? 'var(--color-green)' : 'var(--border-light)'}`,
                      cursor: task.completed ? 'default' : 'pointer',
                      transition: 'all 0.2s ease'
                    }}
                  >
                    <div style={{
                      width: '24px', height: '24px', borderRadius: '50%',
                      backgroundColor: task.completed ? 'var(--color-green)' : 'var(--bg-card)',
                      color: task.completed ? '#ffffff' : 'var(--text-muted)',
                      display: 'flex', alignItems: 'center', justifyContent: 'center',
                      fontWeight: 'bold', fontSize: '0.8rem', border: '1.5px solid var(--border-light)'
                    }}>
                      {task.completed ? '✓' : idx + 1}
                    </div>
                    <div style={{ flex: 1 }}>
                      <h5 style={{
                        fontSize: '0.92rem', fontWeight: 'bold',
                        textDecoration: task.completed ? 'line-through' : 'none',
                        color: task.completed ? 'var(--color-green-dark)' : 'var(--text-main)',
                        margin: 0
                      }}>{task.topic}</h5>
                      <span style={{ fontSize: '0.72rem', color: 'var(--text-muted)', fontWeight: 'bold' }}>
                        Subject: {task.subject} • Duration: {task.duration} {task.priority && `• Priority: ${task.priority.toUpperCase()}`}
                      </span>
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <div style={{ textAlign: 'center', padding: '30px 15px', color: 'var(--text-muted)' }}>
                <Lightbulb size={36} color="var(--color-purple)" style={{ marginBottom: '10px' }} />
                <p style={{ fontSize: '0.9rem', fontWeight: 'bold', marginBottom: '8px' }}>No active plan for today.</p>
                <p style={{ fontSize: '0.78rem', marginBottom: '15px' }}>
                  Ask our AI orchestrator to organize your topics based on weaknesses and quiz scores!
                </p>
                <button onClick={handleGeneratePlan} className="btn-3d btn-3d-purple" style={{ padding: '8px 20px', fontSize: '0.85rem' }}>
                  ✨ Ask Study Buddy to Plan
                </button>
              </div>
            )}
          </section>

          {/* Upcoming Exams Panel */}
          <section className="card-buddy">
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '1.5px solid var(--border-light)', paddingBottom: '10px', marginBottom: '15px' }}>
              <h3 style={{ fontSize: '1.35rem', display: 'flex', alignItems: 'center', gap: '8px', color: 'var(--text-main)' }}>
                <Calendar size={20} color="var(--color-purple)" /> Upcoming Exams
              </h3>
              <button 
                onClick={() => setShowAddExam(!showAddExam)}
                style={{
                  border: 'none', background: 'none', color: 'var(--color-purple)',
                  fontFamily: 'var(--font-header)', fontWeight: 'bold', cursor: 'pointer',
                  display: 'flex', alignItems: 'center', gap: '2px', fontSize: '0.85rem'
                }}
              >
                <Plus size={14} /> Add Exam
              </button>
            </div>

            {showAddExam && (
              <form onSubmit={handleAddExam} style={{
                padding: '12px', border: '2px dashed var(--color-purple-light)',
                borderRadius: 'var(--radius-sm)', marginBottom: '15px', display: 'flex', flexDirection: 'column', gap: '10px'
              }}>
                <input
                  type="text"
                  placeholder="Exam Title (e.g. Unit Test 1)"
                  value={newExamTitle}
                  onChange={(e) => setNewExamTitle(e.target.value)}
                  style={{
                    padding: '8px 12px', borderRadius: 'var(--radius-sm)', border: '2px solid var(--border-light)',
                    fontSize: '0.85rem', outline: 'none', fontFamily: 'var(--font-body)'
                  }}
                  required
                />
                
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '10px' }}>
                  <select
                    value={newExamSubject}
                    onChange={(e) => setNewExamSubject(e.target.value)}
                    style={{
                      padding: '8px', borderRadius: 'var(--radius-sm)', border: '2px solid var(--border-light)',
                      fontSize: '0.85rem', outline: 'none', fontFamily: 'var(--font-body)'
                    }}
                  >
                    <option value="Mathematics">Mathematics</option>
                    <option value="Science">Science</option>
                    <option value="English">English</option>
                    <option value="Social Studies">Social Studies</option>
                    <option value="Telugu">Telugu</option>
                    <option value="Hindi">Hindi</option>
                  </select>
                  
                  <input
                    type="date"
                    value={newExamDate}
                    onChange={(e) => setNewExamDate(e.target.value)}
                    style={{
                      padding: '8px', borderRadius: 'var(--radius-sm)', border: '2px solid var(--border-light)',
                      fontSize: '0.85rem', outline: 'none', fontFamily: 'var(--font-body)'
                    }}
                    required
                  />
                </div>

                <div style={{ display: 'flex', gap: '8px', justifyContent: 'flex-end' }}>
                  <button type="button" onClick={() => setShowAddExam(false)} style={{
                    padding: '6px 12px', background: 'none', border: '2px solid var(--border-light)',
                    borderRadius: 'var(--radius-sm)', fontSize: '0.8rem', cursor: 'pointer', fontWeight: 'bold'
                  }}>Cancel</button>
                  <button type="submit" className="btn-3d btn-3d-purple" style={{ padding: '6px 16px', fontSize: '0.8rem' }}>Save Exam</button>
                </div>
              </form>
            )}

            {exams.length === 0 ? (
              <p style={{ color: 'var(--text-muted)', fontSize: '0.85rem', fontStyle: 'italic', textAlign: 'center', padding: '15px 0' }}>
                No upcoming exams scheduled. Enjoy studying! 🎉
              </p>
            ) : (
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '15px' }}>
                {exams.map((exam) => (
                  <div 
                    key={exam._id} 
                    style={{
                      padding: '14px', borderRadius: 'var(--radius-sm)',
                      border: '1.5px solid var(--border-light)',
                      backgroundColor: 'var(--bg-card)',
                      display: 'flex', justifyContent: 'space-between', alignItems: 'start'
                    }}
                  >
                    <div>
                      <span style={{
                        backgroundColor: 'var(--color-purple-light)', color: 'var(--color-purple-dark)',
                        fontSize: '0.65rem', fontWeight: 'bold', padding: '2px 6px', borderRadius: '4px', textTransform: 'uppercase'
                      }}>
                        {exam.subject}
                      </span>
                      <h5 style={{ margin: '5px 0 2px 0', fontSize: '0.9rem', fontWeight: 'bold', color: 'var(--text-main)' }}>
                        {exam.title}
                      </h5>
                      <span style={{ fontSize: '0.72rem', color: 'var(--color-red-dark)', fontWeight: 'bold', display: 'flex', alignItems: 'center', gap: '2px' }}>
                        <Clock size={10} /> Date: {exam.date}
                      </span>
                    </div>
                    <button 
                      onClick={() => handleDeleteExam(exam._id)}
                      style={{ background: 'none', border: 'none', color: 'var(--text-muted)', cursor: 'pointer', padding: '4px' }}
                      title="Remove exam"
                    >
                      <Trash size={14} />
                    </button>
                  </div>
                ))}
              </div>
            )}
          </section>

        </div>

        {/* Right Column: Weak Subjects, Homework, Reminders, Mascot */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '30px' }}>
          
          {/* Weak Subjects Card */}
          <section className="card-buddy" style={{ background: 'linear-gradient(135deg, #fffbee 0%, #fff3d0 100%)', borderColor: '#ffe0b2' }}>
            <h3 style={{ fontSize: '1.2rem', marginBottom: '12px', display: 'flex', alignItems: 'center', gap: '6px', color: 'var(--text-main)' }}>
              <AlertTriangle size={18} color="var(--color-yellow-dark)" /> Memory Subsystem Profile
            </h3>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '10px', fontSize: '0.85rem' }}>
              <div>
                <span style={{ fontWeight: 'bold', color: 'var(--text-muted)' }}>School Info:</span>
                <p style={{ margin: '2px 0 0 0', fontWeight: '600' }}>
                  {studentProfile.schoolName || 'Zilla Parishad High School'} ({studentProfile.schoolType})
                </p>
              </div>
              <div style={{ display: 'flex', gap: '20px' }}>
                <div>
                  <span style={{ fontWeight: 'bold', color: 'var(--text-muted)' }}>Board:</span>
                  <p style={{ margin: '2px 0 0 0', fontWeight: '600' }}>{studentProfile.board}</p>
                </div>
                <div>
                  <span style={{ fontWeight: 'bold', color: 'var(--text-muted)' }}>Language:</span>
                  <p style={{ margin: '2px 0 0 0', fontWeight: '600' }}>{studentProfile.preferredLanguage}</p>
                </div>
              </div>
              <div>
                <span style={{ fontWeight: 'bold', color: 'var(--text-muted)' }}>Weak Subjects (Action Areas):</span>
                <div style={{ display: 'flex', flexWrap: 'wrap', gap: '6px', marginTop: '4px' }}>
                  {studentProfile.weakSubjects && studentProfile.weakSubjects.length > 0 ? (
                    studentProfile.weakSubjects.map((sub, i) => (
                      <span key={i} style={{ backgroundColor: 'var(--color-red-light)', color: 'var(--color-red-dark)', fontSize: '0.72rem', fontWeight: 'bold', padding: '2px 8px', borderRadius: '10px' }}>
                        {sub}
                      </span>
                    ))
                  ) : (
                    <span style={{ fontStyle: 'italic', color: 'var(--text-muted)' }}>None! Superb!</span>
                  )}
                </div>
              </div>
            </div>
          </section>

          {/* Homework Tracker */}
          <section className="card-buddy">
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '15px' }}>
              <h3 style={{ fontSize: '1.25rem', display: 'flex', alignItems: 'center', gap: '8px', color: 'var(--text-main)' }}>
                <BookOpen size={18} color="var(--color-purple)" /> Homework Tasks
              </h3>
              <button 
                onClick={() => setShowAddHw(!showAddHw)}
                style={{
                  border: 'none', background: 'none', color: 'var(--color-purple)',
                  fontFamily: 'var(--font-header)', fontWeight: 'bold', cursor: 'pointer',
                  display: 'flex', alignItems: 'center', gap: '2px', fontSize: '0.85rem'
                }}
              >
                <Plus size={14} /> Add New
              </button>
            </div>

            {/* Inline Add Homework Form */}
            {showAddHw && (
              <form onSubmit={handleAddHomework} style={{
                padding: '12px', border: '2px dashed var(--color-purple-light)',
                borderRadius: 'var(--radius-sm)', marginBottom: '15px', display: 'flex', flexDirection: 'column', gap: '10px'
              }}>
                <input
                  type="text"
                  placeholder="Homework Title"
                  value={newHwTitle}
                  onChange={(e) => setNewHwTitle(e.target.value)}
                  style={{
                    padding: '8px 12px', borderRadius: 'var(--radius-sm)', border: '2px solid var(--border-light)',
                    fontSize: '0.85rem', outline: 'none', fontFamily: 'var(--font-body)'
                  }}
                  required
                />
                
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '10px' }}>
                  <select
                    value={newHwSubject}
                    onChange={(e) => setNewHwSubject(e.target.value)}
                    style={{
                      padding: '8px', borderRadius: 'var(--radius-sm)', border: '2px solid var(--border-light)',
                      fontSize: '0.85rem', outline: 'none', fontFamily: 'var(--font-body)'
                    }}
                  >
                    <option value="Mathematics">Mathematics</option>
                    <option value="Science">Science</option>
                    <option value="English">English</option>
                    <option value="Social Studies">Social Studies</option>
                    <option value="Telugu">Telugu</option>
                    <option value="Hindi">Hindi</option>
                  </select>
                  
                  <input
                    type="date"
                    value={newHwDueDate}
                    onChange={(e) => setNewHwDueDate(e.target.value)}
                    style={{
                      padding: '8px', borderRadius: 'var(--radius-sm)', border: '2px solid var(--border-light)',
                      fontSize: '0.85rem', outline: 'none', fontFamily: 'var(--font-body)'
                    }}
                    required
                  />
                </div>

                <div style={{ display: 'flex', gap: '8px', justifyContent: 'flex-end' }}>
                  <button type="button" onClick={() => setShowAddHw(false)} style={{
                    padding: '6px 12px', background: 'none', border: '2px solid var(--border-light)',
                    borderRadius: 'var(--radius-sm)', fontSize: '0.8rem', cursor: 'pointer', fontWeight: 'bold'
                  }}>Cancel</button>
                  <button type="submit" className="btn-3d btn-3d-purple" style={{ padding: '6px 16px', fontSize: '0.8rem' }}>Save Task</button>
                </div>
              </form>
            )}

            {homework.length === 0 ? (
              <div style={{ textAlign: 'center', padding: '15px 5px', color: 'var(--text-muted)' }}>
                <CheckCircle size={28} color="var(--color-green)" style={{ marginBottom: '6px' }} />
                <p style={{ fontSize: '0.85rem', fontWeight: '600' }}>No active homework tracked. Great job!</p>
              </div>
            ) : (
              <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
                {homework.slice(0, 3).map((hw) => (
                  <div
                    key={hw._id}
                    style={{
                      display: 'flex', alignItems: 'center', gap: '10px',
                      padding: '10px 12px', borderRadius: 'var(--radius-sm)',
                      border: '1.5px solid var(--border-light)',
                      backgroundColor: hw.completed ? 'rgba(0,0,0,0.02)' : 'var(--bg-card)',
                      opacity: hw.completed ? 0.7 : 1
                    }}
                  >
                    <input
                      type="checkbox"
                      checked={hw.completed}
                      onChange={() => handleToggleHomework(hw._id, hw.completed)}
                      style={{ width: '16px', height: '16px', cursor: 'pointer', accentColor: 'var(--color-purple)' }}
                    />
                    <div style={{ flex: 1 }}>
                      <p style={{
                        fontSize: '0.9rem', fontWeight: '600',
                        textDecoration: hw.completed ? 'line-through' : 'none',
                        color: 'var(--text-main)', margin: 0
                      }}>
                        {hw.title}
                      </p>
                      <div style={{ display: 'flex', gap: '8px', fontSize: '0.72rem', color: 'var(--text-muted)', fontWeight: '500', marginTop: '1px' }}>
                        <span>{hw.subject}</span>
                        <span>•</span>
                        <span style={{ display: 'flex', alignItems: 'center', gap: '2px', color: 'var(--color-red)' }}>
                          <Clock size={10} /> Due: {hw.dueDate}
                        </span>
                      </div>
                    </div>
                    <button 
                      onClick={() => handleDeleteHomework(hw._id)}
                      style={{ background: 'none', border: 'none', color: 'var(--text-muted)', cursor: 'pointer', padding: '4px' }}
                      title="Delete"
                    >
                      <Trash size={14} />
                    </button>
                  </div>
                ))}
              </div>
            )}
          </section>

          {/* Reminder System */}
          <ReminderSystem />

          {/* AI Tutor Motivation Card */}
          <div 
            onClick={() => navigate('chat')}
            style={{
              display: 'flex', alignItems: 'center', gap: '15px',
              backgroundColor: 'var(--color-purple-light)', border: '2px solid var(--color-purple)',
              borderRadius: 'var(--radius-md)', padding: '16px 20px', boxShadow: '0 4px 0 var(--color-purple)',
              cursor: 'pointer', transition: 'all 0.2s'
            }}
            onMouseEnter={(e) => { e.currentTarget.style.transform = 'translateY(-2px)'; }}
            onMouseLeave={(e) => { e.currentTarget.style.transform = 'translateY(0)'; }}
          >
            <Mascot size={60} expression="happy" />
            <div>
              <p style={{ fontSize: '0.88rem', fontWeight: 'bold', color: 'var(--color-purple-dark)', lineHeight: '1.4', margin: 0 }}>
                "Stuck on a topic? Tap here to ask Study Buddy AI. I can teach chapters, create plans, or run custom quizzes!" 🚀
              </p>
            </div>
          </div>

        </div>
      </div>
    </div>
  );
};
